### ISSUE TITLE
About confidence-based Active Retrieval

### ISSUE THREAD

**Issue by xiami2019** [jzbjyb/FLARE#2]
Hi, nice work!
I have a question about how to get a token's probability for confidence-based active retrieval. Can it be obtained from OpenAI's api? Or do we need another white-box model to calculate this probability?

**Comment by tianxiexiaozhu77** [comment]
Excuse me, how to get the probability of token through text-davinci-003.
There are too many bugs, could you re-upload a code that can run successfully.

**Comment by jacksonchen1998** [comment]
@xiami2019 Same question.

**Comment by jzbjyb** [comment]
Sorry for the late reply and thanks @jacksonchen1998 for the pointers!
To be more specific, completion models (such as `text-davinci-003` which is the model used in the paper) returns probabilities of generated tokens if you specify the [logprobs](https://platform.openai.com/docs/api-reference/completions/create#completions/create-logprobs) parameter in the request.
However, chat models (such as `gpt-3.5-turbo`) cannot return probabilities.
