### ISSUE TITLE
prep.py lacks modules import

### ISSUE THREAD

**Issue by baochi0212** [jzbjyb/FLARE#3]
what is models module imported in prep.py ?

**Comment by DongdongY1** [comment]
I suppose "models" should be changed to "src" as you will find all the requisites in folder "src". However, even changing this cannot enable index to be built properly. Too many bugs...

**Comment by jzbjyb** [comment]
Sorry for the late reply and the bugs I made when I release the code.
I just fixed the bugs in the `prep.py` file. Now it should be able to index the wikipedia documents with the following command:
```
python prep.py --task build_elasticsearch --inp data/dpr/psgs_w100.tsv wikipedia_dpr
```
