### ISSUE TITLE
Could you share WikiAsp dataset used in the experiments?

### ISSUE THREAD

**Issue by jihyukkim-nlp** [jzbjyb/FLARE#5]
Hi all, I am Jihyuk, a PhD student interested in retrieval-augmented LLMs.
I appreciate the open-sourcing of codes!

**I am wondering if WikiAsp dataset used in the experiments can also be shared.**

I noticed that the original, open-sourced WikiAsp dataset only includes summaries and reference documents.
But, it does not include inputs, e.g., "Generate a summary about Joe Biden",  which are needed for FLARE.

Best regards,
Jihyuk

**Comment by jzbjyb** [comment]
Thanks for the question and sorry for getting back to you late!
I just uploaded the [WikiAsp dataset](https://github.com/jzbjyb/FLARE/tree/main/data/wikiasp) and added instructions on how to run experiments on this dataset in the readme file.
You need to [setup Bing search](https://github.com/jzbjyb/FLARE#setup-bing-search) before prompting OpenAI models.

**Comment by jihyukkim-nlp** [comment]
Thank you so much for sharing dataset and providing helpful instructions!
