### ISSUE TITLE
How do you get token probability through openai's api

### ISSUE THREAD

**Issue by zhangzhen-research** [jzbjyb/FLARE#7]
How do you get token probability through openai's api

**Comment by jzbjyb** [comment]
Sorry for the late reply! This question is related to [the other issue](https://github.com/jzbjyb/FLARE/issues/2).
Completion models (such as text-davinci-003 which is the model used in the paper) returns probabilities of generated tokens if you specify the [logprobs](https://platform.openai.com/docs/api-reference/completions/create#completions/create-logprobs) parameter in the request.
However, chat models (such as gpt-3.5-turbo) cannot return probabilities.
